basePath: /user
definitions:
  model.Response:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      message:
        example: success
        type: string
    type: object
host: localhost:8890
info:
  contact: {}
  description: 用户注册、登录、邮箱验证码等接口
  title: OpenList 用户服务 API
  version: "1.0"
paths:
  /user/forgot-password/reset:
    post:
      consumes:
      - application/json
      description: 校验验证码并重置密码
      parameters:
      - description: 重置信息
        in: body
        name: reset
        required: true
        schema:
          properties:
            code:
              type: string
            email:
              type: string
            new_password:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 忘记密码-重置密码
      tags:
      - 用户
  /user/forgot-password/send-code:
    post:
      consumes:
      - application/json
      description: 已注册用户发送重置密码验证码
      parameters:
      - description: 邮箱
        in: body
        name: email
        required: true
        schema:
          properties:
            email:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 忘记密码-发送验证码
      tags:
      - 用户
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 登录信息
        in: body
        name: login
        required: true
        schema:
          properties:
            email:
              type: string
            password:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户登录
      tags:
      - 用户
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册并激活账户
      parameters:
      - description: 注册信息
        in: body
        name: register
        required: true
        schema:
          properties:
            code:
              type: string
            email:
              type: string
            password:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 注册并激活
      tags:
      - 用户
  /user/send-code:
    post:
      consumes:
      - application/json
      description: 发送邮箱验证码
      parameters:
      - description: 邮箱
        in: body
        name: email
        required: true
        schema:
          properties:
            email:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 发送验证码
      tags:
      - 用户
swagger: "2.0"
