root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
include_dir = []
kill_delay = "1s"
log = "build-errors.log"
delay = 1000
stop_on_error = true
send_interrupt = false

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

# run configuration
[run]
watcher = ["all"]
listener = "127.0.0.1"
port = 8890
env = []
args = []
