# 日志配置
log:
  # 日志文件路径
  filename: 'logs/main.log'
  # 单个日志文件最大大小，单位MB
  maxSize: 100
  # 保留的旧日志文件最大数量
  maxBackups: 30
  # 保留的旧日志文件最大天数
  maxAge: 30
  # 是否压缩旧日志文件
  compress: true
  # 日志级别: debug, info, warn, error, fatal
  level: 'info'
  # 是否启用控制台输出
  console: false
  # 是否启用文件输出
  file: true
